
from draw_rb_tree import draw_rb_tree
from rbtree import RedBlackTree


# Пример использования:
tree = RedBlackTree()
tree.insert(20)
tree.insert(10)
tree.insert(30)
tree.insert(5)
tree.insert(15)
tree.insert(25)
tree.insert(35)
tree.insert(3)
tree.insert(8)
tree.insert(12)
tree.insert(17)
tree.insert(22)
tree.insert(27)
tree.insert(32)
tree.insert(37)
draw_rb_tree(tree).render('rbtree1', format='png', view=True)
tree.insert(38)
draw_rb_tree(tree).render('rbtree2', format='png', view=True)
tree.insert(39)
draw_rb_tree(tree).render('rbtree3', format='png', view=True)
tree.insert(40)
draw_rb_tree(tree).render('rbtree4', format='png', view=True)
tree.insert(42)
draw_rb_tree(tree).render('rbtree5', format='png', view=True)
tree.insert(44)
draw_rb_tree(tree).render('rbtree6', format='png', view=True)
tree.insert(46)
draw_rb_tree(tree).render('rbtree7', format='png', view=True)
tree.insert(48)
draw_rb_tree(tree).render('rbtree8', format='png', view=True)
tree.insert(49)
draw_rb_tree(tree).render('rbtree9', format='png', view=True)
tree.insert(50)
draw_rb_tree(tree).render('rbtree10', format='png', view=True)
tree.insert(51)
draw_rb_tree(tree).render('rbtree11', format='png', view=True)
tree.insert(52)
draw_rb_tree(tree).render('rbtree12', format='png', view=True)
tree.insert(53)
draw_rb_tree(tree).render('rbtree13', format='png', view=True)
tree.insert(54)
draw_rb_tree(tree).render('rbtree14', format='png', view=True)

# draw_rb_tree(tree).render('rbtree', format='png', view=True)

